import 'package:flutter/material.dart';

import '../../core/constants/colors.dart';

class AppTheme {
  const AppTheme._();
  static final ThemeData lightTheme = ThemeData(
    useMaterial3: true,
    colorScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: AppColors.lightPrimary,
      onPrimary: AppColors.lightOnPrimary,
      primaryContainer: AppColors.lightPrimaryContainer,
      onPrimaryContainer: AppColors.lightOnPrimaryContainer,
      secondary: AppColors.lightSecondary,
      onSecondary: AppColors.lightOnSecondary,
      secondaryContainer: AppColors.lightSecondaryContainer,
      onSecondaryContainer: AppColors.lightOnSecondaryContainer,
      tertiary: AppColors.lightTertiary,
      onTertiary: AppColors.lightOnTertiary,
      tertiaryContainer: AppColors.lightTertiaryContainer,
      onTertiaryContainer: AppColors.lightOnTertiaryContainer,
      error: AppColors.lightError,
      errorContainer: AppColors.lightErrorContainer,
      onError: AppColors.lightOnError,
      onErrorContainer: AppColors.lightOnErrorContainer,
      background: AppColors.lightBackground,
      onBackground: AppColors.lightOnBackground,
      surface: AppColors.lightSurface,
      onSurface: AppColors.lightOnSurface,
      surfaceVariant: AppColors.lightSurfaceVariant,
      onSurfaceVariant: AppColors.lightOnSurfaceVariant,
      outline: AppColors.lightOutline,
      onInverseSurface: AppColors.lightOnInverseSurface,
      inverseSurface: AppColors.lightInverseSurface,
      inversePrimary: AppColors.lightInversePrimary,
      shadow: AppColors.lightShadow,
      surfaceTint: AppColors.lightSurfaceTint,
      outlineVariant: AppColors.lightOutlineVariant,
      scrim: AppColors.lightScrim,
    ),
    chipTheme: const ChipThemeData(
      side: BorderSide.none,
    ),
  );

  static final ThemeData darkTheme = ThemeData(
    useMaterial3: true,
    colorScheme: const ColorScheme(
      brightness: Brightness.dark,
      primary: AppColors.darkPrimary,
      onPrimary: AppColors.darkOnPrimary,
      primaryContainer: AppColors.darkPrimaryContainer,
      onPrimaryContainer: AppColors.darkOnPrimaryContainer,
      secondary: AppColors.darkSecondary,
      onSecondary: AppColors.darkOnSecondary,
      secondaryContainer: AppColors.darkSecondaryContainer,
      onSecondaryContainer: AppColors.darkOnSecondaryContainer,
      tertiary: AppColors.darkTertiary,
      onTertiary: AppColors.darkOnTertiary,
      tertiaryContainer: AppColors.darkTertiaryContainer,
      onTertiaryContainer: AppColors.darkOnTertiaryContainer,
      error: AppColors.darkError,
      errorContainer: AppColors.darkErrorContainer,
      onError: AppColors.darkOnError,
      onErrorContainer: AppColors.darkOnErrorContainer,
      background: AppColors.darkBackground,
      onBackground: AppColors.darkOnBackground,
      surface: AppColors.darkSurface,
      onSurface: AppColors.darkOnSurface,
      surfaceVariant: AppColors.darkSurfaceVariant,
      onSurfaceVariant: AppColors.darkOnSurfaceVariant,
      outline: AppColors.darkOutline,
      onInverseSurface: AppColors.darkOnInverseSurface,
      inverseSurface: AppColors.darkInverseSurface,
      inversePrimary: AppColors.darkInversePrimary,
      shadow: AppColors.darkShadow,
      surfaceTint: AppColors.darkSurfaceTint,
      outlineVariant: AppColors.darkOutlineVariant,
      scrim: AppColors.darkScrim,
    ),
  );
}
